services:
  shopping-cart:
    image: nadinechancay/shopping-cart
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    container_name: shopping-cart
    networks:
      - shopping-cart_net

networks:
  shopping-cart_net:
    driver: bridge