"""Initial migration

Revision ID: 969286c4b8b4
Revises: 
Create Date: 2024-12-20 00:14:35.090959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969286c4b8b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('UserId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('PasswordExpirationDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UserId', name='Accounts_pkey')
    )
    # ### end Alembic commands ###
